### ISSUE TITLE
Add public constant for `asctime` format string

### ISSUE THREAD

**Issue by lopopolo** [artichoke/strftime-ruby#35]
https://github.com/ruby/ruby/blob/v3_1_2/time.c#L3975-L3990

Add a public constant for the `asctime` format string from Ruby and `time.h` in C. This constant should have docs, an examples section that shows the formatted output, and tests.

**Comment by x-hgg-x** [comment]
This is the same as the `%c` specifier.

**Comment by lopopolo** [comment]
Awesome. I still think I'd like a named constant as part of the API to make it a bit more obvious how to replicate the `asctime` C API.
