### ISSUE TITLE
Discuss post-v1.0.0 release strategy

### ISSUE THREAD

**Issue by lopopolo** [artichoke/strftime-ruby#66]
I think this crate is pretty complete, but we can't know for sure.

If we find the need to make changes, quality improvements, fix bugs, or accept PRs from outside contributors, how should we be releasing them?

One thing to keep in mind that as a trait-based API, we'll want to try really hard to avoid bumping the semver-major version (unless we do the semver trick).

**Comment by x-hgg-x** [comment]
I think bug fixes should be released as patch versions as soon as possible.

The API is still relatively small, so it should be ok to add other versions of `strftime` in separate modules if needed, then release with a minor version increase.

However, we should not change the signature of the `Time` trait to avoid breaking changes.

**Comment by lopopolo** [comment]
Agreed. Let's do this.
